# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
# -   repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v3.2.0
#     hooks:
#     -   id: trailing-whitespace
#     -   id: end-of-file-fixer
#     -   id: check-yaml
#     -   id: check-added-large-files
- repo: local
  hooks:
  - id: ruff_format
    name: ruff format
    entry: poetry run ruff format
    language: system
    types: [python]
    require_serial: true
  - id: ruff_lint
    name: ruff lint
    entry: poetry run ruff check
    language: system
    types: [python]
    require_serial: true
  - id: pytest
    name: pytest
    entry: poetry run pytest tests
    language: system
    types: [text]
    files: \.(py|cgx)$
    require_serial: true
    pass_filenames: false
