[tool.poetry]
name = "kolla"
version = "0.5.2"
description = "Reactive user interfaces"
authors = ["Berend Klein Haneveld <berendkleinhaneveld@gmail.com>", "Korijn van Golen <korijn@gmail.com>"]
license = "MIT"
homepage = "https://github.com/fork-tongue/kolla"
readme = "README.md"

[tool.poetry.extras]
pygfx = ["pygfx"]
pyside = ["pyside6_essentials"]

[tool.poetry.dependencies]
python = ">=3.9"
observ = ">=0.9.5"
pygfx = { version = ">=0.1.9", optional = true }
pyside6_essentials = { version = "^6.3", python = "<3.11", optional = true }

# TODO: add entry_point to be able to run kolla as module and render .kolla files directly
# python -m kolla path/to/example.kolla

[tool.poetry.group.dev.dependencies]
black = "*"
flake8 = "*"
flake8-black = "*"
flake8-import-order = "*"
flake8-print = "*"
pre-commit = "*"
pytest = "*"
pytest-cov = "*"
pytest-qt = "*"
pytest-random-order = "*"
pytest-xvfb = "*"
rich = {version = "*", python = "<4.0"}
isort = {version = "*", python = "<4.0"}

[tool.coverage.run]
omit = [
	"tests/*",
	"kolla/renderers/*"
]

[tool.isort]
ensure_newline_before_comments = true
force_grid_wrap = 0
force_sort_within_sections = true
group_by_package = true
include_trailing_comma = true
lexicographical = true
line_length = 88
lines_after_imports = 2
multi_line_output = 3
no_lines_before = 'LOCALFOLDER'
order_by_type = false
reverse_relative = true
skip_gitignore = true
use_parentheses = true
combine_as_imports = true

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
